// Static metadata for surahs, reciters, fonts and translations
export const SURAHS: { number: number; name: string; ayahs: number }[] = [
  { number: 1, name: "الفاتحة", ayahs: 7 },
  { number: 2, name: "البقرة", ayahs: 286 },
  { number: 3, name: "آل عمران", ayahs: 200 },
  { number: 4, name: "النساء", ayahs: 176 },
  { number: 5, name: "المائدة", ayahs: 120 },
  { number: 6, name: "الأنعام", ayahs: 165 },
  { number: 7, name: "الأعراف", ayahs: 206 },
  { number: 8, name: "الأنفال", ayahs: 75 },
  { number: 9, name: "التوبة", ayahs: 129 },
  { number: 10, name: "يونس", ayahs: 109 },
  { number: 11, name: "هود", ayahs: 123 },
  { number: 12, name: "يوسف", ayahs: 111 },
  { number: 13, name: "الرعد", ayahs: 43 },
  { number: 14, name: "إبراهيم", ayahs: 52 },
  { number: 15, name: "الحجر", ayahs: 99 },
  { number: 16, name: "النحل", ayahs: 128 },
  { number: 17, name: "الإسراء", ayahs: 111 },
  { number: 18, name: "الكهف", ayahs: 110 },
  { number: 19, name: "مريم", ayahs: 98 },
  { number: 20, name: "طه", ayahs: 135 },
  { number: 21, name: "الأنبياء", ayahs: 112 },
  { number: 22, name: "الحج", ayahs: 78 },
  { number: 23, name: "المؤمنون", ayahs: 118 },
  { number: 24, name: "النور", ayahs: 64 },
  { number: 25, name: "الفرقان", ayahs: 77 },
  { number: 26, name: "الشعراء", ayahs: 227 },
  { number: 27, name: "النمل", ayahs: 93 },
  { number: 28, name: "القصص", ayahs: 88 },
  { number: 29, name: "العنكبوت", ayahs: 69 },
  { number: 30, name: "الروم", ayahs: 60 },
  { number: 31, name: "لقمان", ayahs: 34 },
  { number: 32, name: "السجدة", ayahs: 30 },
  { number: 33, name: "الأحزاب", ayahs: 73 },
  { number: 34, name: "سبأ", ayahs: 54 },
  { number: 35, name: "فاطر", ayahs: 45 },
  { number: 36, name: "يس", ayahs: 83 },
  { number: 37, name: "الصافات", ayahs: 182 },
  { number: 38, name: "ص", ayahs: 88 },
  { number: 39, name: "الزمر", ayahs: 75 },
  { number: 40, name: "غافر", ayahs: 85 },
  { number: 41, name: "فصلت", ayahs: 54 },
  { number: 42, name: "الشورى", ayahs: 53 },
  { number: 43, name: "الزخرف", ayahs: 89 },
  { number: 44, name: "الدخان", ayahs: 59 },
  { number: 45, name: "الجاثية", ayahs: 37 },
  { number: 46, name: "الأحقاف", ayahs: 35 },
  { number: 47, name: "محمد", ayahs: 38 },
  { number: 48, name: "الفتح", ayahs: 29 },
  { number: 49, name: "الحجرات", ayahs: 18 },
  { number: 50, name: "ق", ayahs: 45 },
  { number: 51, name: "الذاريات", ayahs: 60 },
  { number: 52, name: "الطور", ayahs: 49 },
  { number: 53, name: "النجم", ayahs: 62 },
  { number: 54, name: "القمر", ayahs: 55 },
  { number: 55, name: "الرحمن", ayahs: 78 },
  { number: 56, name: "الواقعة", ayahs: 96 },
  { number: 57, name: "الحديد", ayahs: 29 },
  { number: 58, name: "المجادلة", ayahs: 22 },
  { number: 59, name: "الحشر", ayahs: 24 },
  { number: 60, name: "الممتحنة", ayahs: 13 },
  { number: 61, name: "الصف", ayahs: 14 },
  { number: 62, name: "الجمعة", ayahs: 11 },
  { number: 63, name: "المنافقون", ayahs: 11 },
  { number: 64, name: "التغابن", ayahs: 18 },
  { number: 65, name: "الطلاق", ayahs: 12 },
  { number: 66, name: "التحريم", ayahs: 12 },
  { number: 67, name: "الملك", ayahs: 30 },
  { number: 68, name: "القلم", ayahs: 52 },
  { number: 69, name: "الحاقة", ayahs: 52 },
  { number: 70, name: "المعارج", ayahs: 44 },
  { number: 71, name: "نوح", ayahs: 28 },
  { number: 72, name: "الجن", ayahs: 28 },
  { number: 73, name: "المزمل", ayahs: 20 },
  { number: 74, name: "المدثر", ayahs: 56 },
  { number: 75, name: "القيامة", ayahs: 40 },
  { number: 76, name: "الإنسان", ayahs: 31 },
  { number: 77, name: "المرسلات", ayahs: 50 },
  { number: 78, name: "النبأ", ayahs: 40 },
  { number: 79, name: "النازعات", ayahs: 46 },
  { number: 80, name: "عبس", ayahs: 42 },
  { number: 81, name: "التكوير", ayahs: 29 },
  { number: 82, name: "الانفطار", ayahs: 19 },
  { number: 83, name: "المطففين", ayahs: 36 },
  { number: 84, name: "الانشقاق", ayahs: 25 },
  { number: 85, name: "البروج", ayahs: 22 },
  { number: 86, name: "الطارق", ayahs: 17 },
  { number: 87, name: "الأعلى", ayahs: 19 },
  { number: 88, name: "الغاشية", ayahs: 26 },
  { number: 89, name: "الفجر", ayahs: 30 },
  { number: 90, name: "البلد", ayahs: 20 },
  { number: 91, name: "الشمس", ayahs: 15 },
  { number: 92, name: "الليل", ayahs: 21 },
  { number: 93, name: "الضحى", ayahs: 11 },
  { number: 94, name: "الشرح", ayahs: 8 },
  { number: 95, name: "التين", ayahs: 8 },
  { number: 96, name: "العلق", ayahs: 19 },
  { number: 97, name: "القدر", ayahs: 5 },
  { number: 98, name: "البينة", ayahs: 8 },
  { number: 99, name: "الزلزلة", ayahs: 8 },
  { number: 100, name: "العاديات", ayahs: 11 },
  { number: 101, name: "القارعة", ayahs: 11 },
  { number: 102, name: "التكاثر", ayahs: 8 },
  { number: 103, name: "العصر", ayahs: 3 },
  { number: 104, name: "الهمزة", ayahs: 9 },
  { number: 105, name: "الفيل", ayahs: 5 },
  { number: 106, name: "قريش", ayahs: 4 },
  { number: 107, name: "الماعون", ayahs: 7 },
  { number: 108, name: "الكوثر", ayahs: 3 },
  { number: 109, name: "الكافرون", ayahs: 6 },
  { number: 110, name: "النصر", ayahs: 3 },
  { number: 111, name: "المسد", ayahs: 5 },
  { number: 112, name: "الإخلاص", ayahs: 4 },
  { number: 113, name: "الفلق", ayahs: 5 },
  { number: 114, name: "الناس", ayahs: 6 },
]

// Comprehensive Arab reciters list from everyayah.com — with qira'at (readings) noted.
// Default reading is "حفص عن عاصم" unless stated otherwise.
export const RECITERS: { id: string; name: string; reading: string }[] = [
  // ===== حفص عن عاصم =====
  { id: "Alafasy_128kbps", name: "مشاري راشد العفاسي", reading: "حفص عن عاصم" },
  { id: "Abdul_Basit_Murattal_192kbps", name: "عبد الباسط عبد الصمد (مرتل)", reading: "حفص عن عاصم" },
  { id: "Abdul_Basit_Mujawwad_128kbps", name: "عبد الباسط عبد الصمد (مجود)", reading: "حفص عن عاصم" },
  { id: "Abdullah_Basfar_192kbps", name: "عبد الله بصفر", reading: "حفص عن عاصم" },
  { id: "Abdullah_Matroud_128kbps", name: "عبد الله المطرود", reading: "حفص عن عاصم" },
  { id: "Abdurrahmaan_As-Sudais_192kbps", name: "عبد الرحمن السديس", reading: "حفص عن عاصم" },
  { id: "Abdul_Wadood_Haneef_128kbps", name: "عبد الودود حنيف", reading: "حفص عن عاصم" },
  { id: "Abdullaah_3awwaad_Al-Juhaynee_128kbps", name: "عبد الله عواد الجهني", reading: "حفص عن عاصم" },
  { id: "Abu_Bakr_Ash-Shaatree_128kbps", name: "أبو بكر الشاطري", reading: "حفص عن عاصم" },
  { id: "Ahmed_ibn_Ali_al-Ajamy_128kbps_ketaballah.net", name: "أحمد بن علي العجمي", reading: "حفص عن عاصم" },
  { id: "Ahmed_Neana_128kbps", name: "أحمد نعينع", reading: "حفص عن عاصم" },
  { id: "Akram_AlAlaqimy_128kbps", name: "أكرم العلاقمي", reading: "حفص عن عاصم" },
  { id: "Ali_Hajjaj_AlSuesy_128kbps", name: "علي حجاج السويسي", reading: "حفص عن عاصم" },
  { id: "Ali_Jaber_64kbps", name: "علي جابر", reading: "حفص عن عاصم" },
  { id: "Aziz_Alili_128kbps", name: "عزيز عليلي", reading: "حفص عن عاصم" },
  { id: "Fares_Abbad_64kbps", name: "فارس عباد", reading: "حفص عن عاصم" },
  { id: "Ghamadi_40kbps", name: "سعد الغامدي", reading: "حفص عن عاصم" },
  { id: "Hani_Rifai_192kbps", name: "هاني الرفاعي", reading: "حفص عن عاصم" },
  { id: "Hudhaify_128kbps", name: "علي بن عبد الرحمن الحذيفي", reading: "حفص عن عاصم" },
  { id: "Husary_128kbps", name: "محمود خليل الحصري (مرتل)", reading: "حفص عن عاصم" },
  { id: "Husary_Mujawwad_64kbps", name: "محمود خليل الحصري (مجود)", reading: "حفص عن عاصم" },
  { id: "Ibrahim_Akhdar_32kbps", name: "إبراهيم الأخضر", reading: "حفص عن عاصم" },
  { id: "Karim_Mansoori_40kbps", name: "كريم منصوري", reading: "حفص عن عاصم" },
  { id: "Khaalid_Abdullaah_al-Qahtaanee_192kbps", name: "خالد القحطاني", reading: "حفص عن عاصم" },
  { id: "Maher_AlMuaiqly_64kbps", name: "ماهر المعيقلي", reading: "حفص عن عاصم" },
  { id: "MaherAlMuaiqly128kbps", name: "ماهر المعيقلي (جودة عالية)", reading: "حفص عن عاصم" },
  { id: "Mahmoud_Ali_Al_Banna_32kbps", name: "محمود علي البنا", reading: "حفص عن عاصم" },
  { id: "Menshawi_32kbps", name: "محمد صديق المنشاوي (32k)", reading: "حفص عن عاصم" },
  { id: "Minshawy_Murattal_128kbps", name: "محمد صديق المنشاوي (مرتل)", reading: "حفص عن عاصم" },
  { id: "Minshawy_Mujawwad_192kbps", name: "محمد صديق المنشاوي (مجود)", reading: "حفص عن عاصم" },
  { id: "Mohammad_al_Tablaway_128kbps", name: "محمد الطبلاوي", reading: "حفص عن عاصم" },
  { id: "Muhammad_AbdulKareem_128kbps", name: "محمد عبد الكريم", reading: "حفص عن عاصم" },
  { id: "Muhammad_Ayyoub_128kbps", name: "محمد أيوب", reading: "حفص عن عاصم" },
  { id: "Muhammad_Jibreel_128kbps", name: "محمد جبريل", reading: "حفص عن عاصم" },
  { id: "Muhsin_Al_Qasim_192kbps", name: "محسن القاسم", reading: "حفص عن عاصم" },
  { id: "Mustafa_Ismail_48kbps", name: "مصطفى إسماعيل", reading: "حفص عن عاصم" },
  { id: "Nasser_Alqatami_128kbps", name: "ناصر القطامي", reading: "حفص عن عاصم" },
  { id: "Sahl_Yassin_128kbps", name: "سهل ياسين", reading: "حفص عن عاصم" },
  { id: "Salaah_AbdulRahman_Bukhatir_128kbps", name: "صلاح بوخاطر", reading: "حفص عن عاصم" },
  { id: "Salah_Al_Budair_128kbps", name: "صلاح البدير", reading: "حفص عن عاصم" },
  { id: "Saood_ash-Shuraym_128kbps", name: "سعود الشريم", reading: "حفص عن عاصم" },
  { id: "Yaser_Salamah_128kbps", name: "ياسر سلامة", reading: "حفص عن عاصم" },
  { id: "Yasser_Ad-Dussary_128kbps", name: "ياسر الدوسري", reading: "حفص عن عاصم" },
  { id: "Yasser_Al-Mazroyee_128kbps", name: "ياسر المزروعي", reading: "حفص عن عاصم" },
  { id: "AbdulSamad_64kbps_QuranExplorer.Com", name: "عبد الباسط عبد الصمد (QE)", reading: "حفص عن عاصم" },

  // ===== ورش عن نافع =====
  { id: "warsh/Yassin_al-Jazaeri_64kbps", name: "ياسين الجزائري", reading: "ورش عن نافع" },
  { id: "warsh/Ibrahim_Al_Akhdar_32kbps", name: "إبراهيم الأخضر", reading: "ورش عن نافع" },

  // ===== قالون عن نافع =====
  { id: "qaloon/Mahmood_Khaleel_Al-Husaree_64kbps", name: "محمود خليل الحصري", reading: "قالون عن نافع" },

  // ===== شعبة عن عاصم =====
  { id: "shouba/Mahmood_Khaleel_Al-Husaree_64kbps", name: "محمود خليل الحصري", reading: "شعبة عن عاصم" },

  // ===== الدوري عن أبي عمرو =====
  { id: "aldoosary_128kbps", name: "محمود الدوسري", reading: "حفص عن عاصم" },
]

// Multiple Arabic fonts users can choose from. Each entry has a Google Fonts ttf URL
// that will be downloaded once into assets/fonts on first use.
export const FONTS: {
  id: string
  name: string // display in UI
  family: string // ASS Fontname value
  file: string // local filename to save as
  url: string
}[] = [
  {
    id: "amiri",
    name: "Amiri — خط أميري كلاسيكي",
    family: "Amiri",
    file: "Amiri-Regular.ttf",
    url: "https://raw.githubusercontent.com/google/fonts/main/ofl/amiri/Amiri-Regular.ttf",
  },
  {
    id: "amiri-quran",
    name: "Amiri Quran — مصحف",
    family: "Amiri Quran",
    file: "AmiriQuran-Regular.ttf",
    url: "https://raw.githubusercontent.com/google/fonts/main/ofl/amiriquran/AmiriQuran-Regular.ttf",
  },
  {
    id: "scheherazade",
    name: "Scheherazade New — مصحف واضح",
    family: "Scheherazade New",
    file: "ScheherazadeNew-Regular.ttf",
    url: "https://raw.githubusercontent.com/google/fonts/main/ofl/scheherazadenew/ScheherazadeNew-Regular.ttf",
  },
  {
    id: "noto-naskh",
    name: "Noto Naskh Arabic — نسخ",
    family: "Noto Naskh Arabic",
    file: "NotoNaskhArabic-Regular.ttf",
    url: "https://raw.githubusercontent.com/google/fonts/main/ofl/notonaskharabic/NotoNaskhArabic%5Bwght%5D.ttf",
  },
  {
    id: "reem-kufi",
    name: "Reem Kufi — كوفي حديث",
    family: "Reem Kufi",
    file: "ReemKufi-Regular.ttf",
    url: "https://raw.githubusercontent.com/google/fonts/main/ofl/reemkufi/ReemKufi%5Bwght%5D.ttf",
  },
  {
    id: "aref-ruqaa",
    name: "Aref Ruqaa — رقعة",
    family: "Aref Ruqaa",
    file: "ArefRuqaa-Regular.ttf",
    url: "https://raw.githubusercontent.com/google/fonts/main/ofl/arefruqaa/ArefRuqaa-Regular.ttf",
  },
  {
    id: "cairo",
    name: "Cairo — حديث",
    family: "Cairo",
    file: "Cairo-Regular.ttf",
    url: "https://raw.githubusercontent.com/google/fonts/main/ofl/cairo/Cairo%5Bslnt%2Cwght%5D.ttf",
  },
  {
    id: "tajawal",
    name: "Tajawal — عصري",
    family: "Tajawal",
    file: "Tajawal-Regular.ttf",
    url: "https://raw.githubusercontent.com/google/fonts/main/ofl/tajawal/Tajawal-Regular.ttf",
  },
  {
    id: "lateef",
    name: "Lateef — لطيف",
    family: "Lateef",
    file: "Lateef-Regular.ttf",
    url: "https://raw.githubusercontent.com/google/fonts/main/ofl/lateef/Lateef-Regular.ttf",
  },
  {
    id: "mada",
    name: "Mada — هندسي",
    family: "Mada",
    file: "Mada-Regular.ttf",
    url: "https://raw.githubusercontent.com/google/fonts/main/ofl/mada/Mada-Regular.ttf",
  },
  {
    id: "markazi",
    name: "Markazi Text — مركزي",
    family: "Markazi Text",
    file: "MarkaziText-Regular.ttf",
    url: "https://raw.githubusercontent.com/google/fonts/main/ofl/markazitext/MarkaziText%5Bwght%5D.ttf",
  },
  {
    id: "el-messiri",
    name: "El Messiri — مسيري",
    family: "El Messiri",
    file: "ElMessiri-Regular.ttf",
    url: "https://raw.githubusercontent.com/google/fonts/main/ofl/elmessiri/ElMessiri%5Bwght%5D.ttf",
  },
]

// Optional translation editions (alquran.cloud)
export const TRANSLATIONS: { id: string; name: string }[] = [
  { id: "none", name: "بدون ترجمة" },
  { id: "en.sahih", name: "English — Saheeh International" },
  { id: "en.pickthall", name: "English — Pickthall" },
  { id: "en.yusufali", name: "English — Yusuf Ali" },
  { id: "en.asad", name: "English — Muhammad Asad" },
  { id: "fr.hamidullah", name: "Français — Hamidullah" },
  { id: "es.cortes", name: "Español — Cortes" },
  { id: "de.aburida", name: "Deutsch — Abu Rida" },
  { id: "it.piccardo", name: "Italiano — Piccardo" },
  { id: "pt.elhayek", name: "Português — El-Hayek" },
  { id: "ru.kuliev", name: "Русский — Kuliev" },
  { id: "tr.diyanet", name: "Türkçe — Diyanet" },
  { id: "ur.junagarhi", name: "اردو — Junagarhi" },
  { id: "ur.maududi", name: "اردو — Maududi" },
  { id: "id.indonesian", name: "Bahasa Indonesia" },
  { id: "ms.basmeih", name: "Bahasa Melayu — Basmeih" },
  { id: "sq.nahi", name: "Shqip — Nahi" },
  { id: "bg.theophanov", name: "Български — Theophanov" },
  { id: "bn.bengali", name: "বাংলা — Bengali" },
  { id: "fa.makarem", name: "فارسی — Makarem" },
]

// Background presets. Only Islamically-safe styles: solid colors, gradients and
// abstract geometric/pattern videos. No human/animal imagery.
export const BACKGROUND_TYPES: { id: string; name: string }[] = [
  { id: "gradient", name: "تدرج لوني" },
  { id: "solid", name: "لون صلب" },
  { id: "animated", name: "تدرج متحرك (طبيعة)" },
  { id: "noise", name: "خامة هادئة" },
  { id: "file", name: "ملف خلفية محلي (يجب أن يكون متوافقاً شرعياً)" },
]
